In [1]:
import os
from sklearn.feature_extraction.text import CountVectorizer
from wordcloud import WordCloud
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import regex as re
import math
import json

from matplotlib.ticker import MultipleLocator

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from reportlab.lib.utils import ImageReader

from stream_analysis.env_ import Env_
from stream_analysis.chat import Chat
from stream_analysis.summary import Summary
from stream_analysis.utils import minutes_to_hhmm

%matplotlib inline

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/73/n7k_y4h56h10pfdmrd37l8n40000gn/T/ipykernel_89379/2594286275.py", line 21, in <module>
    from stream_analysis.chat import Chat
  File "/Users/kai/Documents/StreamResearch/stream_analysis/chat.py", line 894, in <module>
    from stream_analysis.types.message import Message
  File "/Users/kai/Documents/StreamResearch/stream_analysis/types/message.py", line 3, in <module>
    from stream_analysis.analyzer import get_sentiment
  File "/Users/kai/Documents/StreamResearch/stream_analysis/analyzer.py", line 1, in <module>
    from transformers import AutoModelForSequenceClassification
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/transformers/utils/__init__.py", line 27, in <module>
    from .chat_template_utils import DocstringParsingException, TypeHintParsingException, get_json_schema
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/transformers/utils/chat_template_utils.py", line 39, in <module>
    from torch import Tensor
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/kai/Documents/StreamResearch/.venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [2]:
def get_word_freq(array):
    text_vectorizer = CountVectorizer(stop_words='english', encoding='utf8')
    X = text_vectorizer.fit_transform(array)
    word_freq = pd.DataFrame(
        X.toarray(), columns=text_vectorizer.get_feature_names_out())
    word_freq = word_freq.sum().sort_values(ascending=False)
    return word_freq


def draw_markdown_to_pdf(canvas, text, cursor, margin, width, height, font_name):
    # 轉換 Markdown 到純文本
    paragraphs = text.split('\n')

    canvas.setFont(font_name, 8)
    for paragraph in paragraphs:
        lines = paragraph.split('\n')
        for line in lines:
            # 計算每一行文本的寬度並進行多行處理
            if cursor < 50:  # 確保不超出頁面底部
                canvas.showPage()
                cursor = height - 50
            text_width = canvas.stringWidth(line, font_name, 12)
            if text_width > width:
                # 如果行寬超出可用寬度，進行換行處理
                words = line.split(' ')
                current_line = ""
                for word in words:
                    if canvas.stringWidth(current_line + word, font_name, 12) > width:
                        canvas.drawString(margin, cursor, current_line.strip())
                        cursor -= 15
                        current_line = word + ' '
                    else:
                        current_line += word + ' '
                if current_line:
                    canvas.drawString(margin, cursor, current_line.strip())
                    cursor -= 15
            else:
                canvas.drawString(margin, cursor, line.strip())
                cursor -= 15
    return cursor

In [6]:
env_ = Env_(video_live_url='https://www.youtube.com/live/YpSgByhKEVI?si=VYesmexoIwPYtMHe')

with open(env_.video_data_path, 'w', encoding='utf8') as f:
    json.dump(env_.video_data, f, indent=2, ensure_ascii=False)

In [7]:
chat = Chat(env_)
df = chat.get()
chat.df_per_min.to_csv(env_.chat_per_min_csv_path, index=False)

In [8]:
chat.hightlight_urls

['https://youtube.com/watch?v=YpSgByhKEVI&t=0m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=21m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=35m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=40m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=45m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=53m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=64m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=75m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=85m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=95m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=107m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=114m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=133m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=138m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=143m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=151m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=161m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=172m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=189m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=194m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=208m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=213m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=221m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=238m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=250m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=264m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=275m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=281m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=303m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=313m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=322m',
 'https://youtube.com/watch?v=YpSgByhKEVI&t=333m']

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38044 entries, 0 to 38043
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   author_id                   38044 non-null  object
 1   author_name                 38044 non-null  object
 2   author_title                38044 non-null  object
 3   author_membership_duration  38044 non-null  int64
 4   author_badge                38044 non-null  object
 5   author_image                38044 non-null  object
 6   message                     38044 non-null  object
 7   message_without_emotes      38044 non-null  object
 8   cleaned_message             38044 non-null  object
 9   message_type                38044 non-null  object
 10  money                       38044 non-null  float64
 11  positive                    38044 non-null  float64
 12  neutral                     38044 non-null  float64
 13  negative                    38044 non-null  float64
 14  sentiment                   0 non-null      object
 15  time_in_seconds             38044 non-null  float64
 16  timestamp                   38044 non-null  int64
 17  time_in_minutes             38044 non-null  int64
dtypes: float64(5), int64(3), object(10)
memory usage: 5.2+ MB

In [10]:
df.head()

,author_id,author_name,author_title,author_membership_duration,author_badge,author_image,message,message_without_emotes,cleaned_message,message_type,money,positive,neutral,negative,sentiment,time_in_seconds,timestamp,time_in_minutes
0,UCYzZ4LtduaAcdtmK0C0fUYg,JustJester🗿,member,180,https://yt3.ggpht.com/JOkdyX8ggHhCfyrJwPOU3hw7...,https://yt4.ggpht.com/-o-Ee1PA-IQ9JKwAcptmxi1_...,:_bijouRee::_bijouRee::_bijouRee:,,,text_message,0.0,0.0,0.0,0.0,None,0.000,1728521764517165,0
1,UCDrY5jIlmYeArYoaxni-T7Q,Joseph Kim,,0,,https://yt4.ggpht.com/BoomnImI__Xk1ozeDVgYmxh6...,I AM SO READY FOR 7 DAYS TO DIE! ITS MY FAVORI...,I AM SO READY FOR 7 DAYS TO DIE! ITS MY FAVORI...,I AM SO READY FOR 7 DAYS TO DIE ITS MY FAVORIT...,text_message,0.0,0.0,0.0,0.0,None,0.883,1728521767244218,0
2,UCp5IDTq7Xokvbd7P_7IVIqQ,CodeEpsilon-5,member,180,https://yt3.ggpht.com/JOkdyX8ggHhCfyrJwPOU3hw7...,https://yt4.ggpht.com/nrvfMhDmOEO-9r5nO9uLuTyu...,:_bijouRee::_bijouRee::_bijouRee:,,,text_message,0.0,0.0,0.0,0.0,None,3.284,1728521769640330,0
3,UCnhhVYLTwyiH7KHHE7E6JeA,moo moo,member,180,https://yt3.ggpht.com/JOkdyX8ggHhCfyrJwPOU3hw7...,https://yt4.ggpht.com/ytc/AIdro_lMFy6jhGBCoNiL...,:_bijouRee::_bijouRee::_bijouRee:,,,text_message,0.0,0.0,0.0,0.0,None,6.018,1728521772327922,0
4,UCGSvkLlNNJT_FYb7xfPHC2w,Ulysses S. Grant,member,365,https://yt3.ggpht.com/h-xO4eXIZA-ivENd6CAG-r3A...,https://yt4.ggpht.com/1rPeKye0FtZdiSyXNzU0rtZi...,:_bijouRee::_bijouRee::_bijouRee::_bijouRee:,,,text_message,0.0,0.0,0.0,0.0,None,7.915,1728521774284486,0

In [11]:
df['message'].nunique()

19843

In [12]:
df_cleaned = df[df['cleaned_message'].str.len() > 0][['author_id', 'message', 'cleaned_message']]
df_cleaned

,author_id,message,cleaned_message
1,UCDrY5jIlmYeArYoaxni-T7Q,I AM SO READY FOR 7 DAYS TO DIE! ITS MY FAVORI...,I AM SO READY FOR 7 DAYS TO DIE ITS MY FAVORIT...
5,UC2RgEqduycII7l25gY727bA,ugggg?,ugggg
7,UCe9ae_M-IN6r1qmDGmi5BlQ,LET'S :_bijouBeep:ING GO:_bijouRee:,ING GO
11,UCi94khy5NeGiu7-9DYJM0Nw,:moai:RIOT:moai:,RIOT
12,UC39KhHUta6-80jHG7roSQUw,BIBOO,BIBOO
...,...,...,...
38033,UCNO-Pp5m8RWePWYH4nMtg-A,rest well biboo,rest well biboo
38034,UC2IxpJlR2uSyNzK54oCtKJw,biboo later,biboo later
38036,UC9ETPMi76j2QmSDs8JUV2NQ,byebye,byebye
38040,UCE6l3aj3jAPViF3qwLWLHdA,Bye bye,Bye bye
38042,UCvfU-cPgNNIYQ9iHTwaASGA,"Sleep well, bijouuu! :_bijouPat::_bijouPat::_b...",Sleep well bijouuu

In [13]:
# from stream_analysis.analyzer import get_sentiment


# msg = df_cleaned['message'].iloc[15]
# display(msg)
# get_sentiment(msg)

'EARLY START :_bijouCheer:'

RuntimeError: Numpy is not available

In [ ]:
df['message_without_emotes'].nunique()

In [ ]:
df['cleaned_message'].nunique()

In [ ]:
chat.df_per_min.info()

In [ ]:
chat.df_per_min.head()

In [ ]:
chat.df_per_min.drop(columns=['time_in_minutes', 'messages_moving_avg']).describe()

In [ ]:
from stream_analysis.charts import ActivityPerMin

activity_per_min = ActivityPerMin(chat, env_)

In [ ]:
chat.df_peaks

In [ ]:
chat.activity_ranges

In [ ]:
plt.figure(figsize=(20, 6))

plt.plot(chat.df_per_min['time_in_minutes'], chat.df_per_min['messages'], label='Total Messages', color='blue')

plt.plot(chat.df_per_min['time_in_minutes'], chat.df_per_min['messages_moving_avg'], label="Moving Average", color='red')

for start, end in chat.activity_ranges:
    plt.axvspan(start, end, color='lightblue', alpha=0.5)
    plt.text(start, chat.df_per_min['messages'].max() * 0.8, minutes_to_hhmm(start), color='blue', fontsize=10, rotation=45)

plt.vlines(0, ymin=0, ymax=chat.df_peaks['messages'].max(), colors='red')

plt.xticks(ticks=env_.time_labels[1], labels=env_.time_labels[0], rotation=45)
plt.gca().xaxis.set_minor_locator(MultipleLocator(1))
plt.xlabel('Time (HH:MM)')
plt.ylabel('Message Count')
plt.title('Number of Messages Per Minute')

plt.grid(True, which='both')
plt.tight_layout()
plt.savefig(env_.chat_timeline_path)
plt.show()

In [20]:
# from stream_analysis.summary import Summary

# df_filtered = df[df['cleaned_message'].str.len() > 0]

# summary = Summary(env_, '\n'.join(df_filtered[['message']].to_numpy().flatten())).getContent()
# summary

In [ ]:
num_intervals = len(chat.activity_ranges)
cols = 3
rows = math.ceil(num_intervals / cols)

fig, axes = plt.subplots(rows, cols, figsize=(18, 3 * rows))

index = -1
for i, time_range in enumerate(chat.activity_ranges):
    try:
        index += 1
        start = time_range[0] * 60
        end = time_range[1] * 60
        start_label = minutes_to_hhmm(time_range[0])
        end_label = minutes_to_hhmm(time_range[1])

        df_filtered = df[(df['time_in_seconds'] >= start) & (df['time_in_seconds'] <= end) & (df['cleaned_message'].str.len() > 0)]

        word_freq = get_word_freq(df_filtered['cleaned_message'])
        word_path = os.path.join(env_.data_path, f'{start_label}_{end_label}'.replace(':', '-'))
        wordcloud = WordCloud(width=800, height=400, background_color='white', max_words=50, min_word_length=3).generate_from_frequencies(word_freq)

        df_filtered[['time_in_seconds', 'message']].to_csv(f'{word_path}_chat.csv', encoding='utf8', index=False)
        word_freq.to_csv(f'{word_path}_wfreq.csv', encoding='utf8', header=False)

        ax = axes[index // cols][index % cols] if rows > 1 else axes[index % cols]

        ax.imshow(wordcloud, interpolation='bilinear')
        ax.axis("off")

        ax.set_title(f'{start_label} - {end_label}', fontsize=14)
    except Exception as e:
        index -= 1
        continue

for j in range(index + 1, rows * cols):
    fig.delaxes(axes[j // cols][j % cols] if rows > 1 else axes[j % cols])

plt.tight_layout()
plt.savefig(env_.chat_wordcloud_path)
plt.show()

In [22]:
font_name = os.getenv('DEFAULT_FONT_NAME')
font_path = f"{os.getenv('DEFAULT_FONT_PATH')}/{font_name}/{os.getenv('DEFAULT_FONT_FILENAME')}"
pdfmetrics.registerFont(TTFont(font_name, font_path, 'utf8'))

c = canvas.Canvas(os.path.join(env_.data_path, 'report.pdf'), pagesize=A4)

width, height = A4
cursor = height
margin = 8
available_width = width - 2 * margin

c.setFont(font_name, 16)

cursor = height - 32

text_width = c.stringWidth(env_.video_title)
x_position = (available_width - text_width) / 2  # 計算置中位置

c.drawString(x_position, cursor, env_.video_title)

c.setFont(font_name, 12)
cursor = cursor - 17
text_width = c.stringWidth(env_.video_liver)
x_position = (available_width - text_width)
c.drawString(x_position, cursor, env_.video_liver)

# cursor = cursor - 10
# cursor = draw_markdown_to_pdf(c, summary, cursor, margin, width, height, font_name)

image = ImageReader(env_.chat_timeline_path)
img_width, img_height = image.getSize()

# 計算圖片縮放比例，保持等比例縮放
scale_factor = available_width / img_width
scaled_width = available_width
scaled_height = img_height * scale_factor

# 如果圖片的高度超過頁面，則根據頁面的高度進行縮放
if scaled_height > height:
    scale_factor = height / img_height
    scaled_height = height
    scaled_width = img_width * scale_factor

# 計算圖片位置（居中顯示圖片）
x_position = margin  # 左右保持 8px 的空格
cursor = y_position = cursor - scaled_height - 10

# 插入圖片
c.drawImage(image, x_position, y_position, width=scaled_width, height=scaled_height)

image = ImageReader(env_.chat_wordcloud_path)
img_width, img_height = image.getSize()

# 計算圖片縮放比例，保持等比例縮放
scale_factor = available_width / img_width
scaled_width = available_width
scaled_height = img_height * scale_factor

# 如果圖片的高度超過頁面，則根據頁面的高度進行縮放
if scaled_height > height:
    scale_factor = height / img_height
    scaled_height = height
    scaled_width = img_width * scale_factor

# 計算圖片位置（居中顯示圖片）
x_position = margin  # 左右保持 8px 的空格
cursor = y_position = cursor - scaled_height - 10

# 插入圖片
c.drawImage(image, x_position, y_position, width=scaled_width, height=scaled_height)

c.save()